config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  resources :posts do
    collection do
      get :generate_report
    end
    member do
      put :approve
      put :reject
      put :submit_for_review
    end
  end

  namespace :users do
    resources :registrations
  end

  namespace :admin do
    resources :users do
      collection do
        patch :assign_admin_role
      end
    end
  end

  root 'posts#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # гость

    if user.admin?
      can :manage, :all # Администраторы могут управлять всем
    else
      can :create, Post # Обычные пользователи могут создавать посты
      can :update, Post, user_id: user.id, status: "draft" # Обычные пользователи могут редактировать только свои черновики
      can :destroy, Post, user_id: user.id, status: "draft" # Обычные пользователи могут удалять только свои черновики
      can :submit_for_approval, Post, user_id: user.id, status: "draft" # Обычные пользователи могут отправить свои посты на проверку
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :post
  mount_uploader :file, FileUploader
end

app/models/post.rb
class Post < ApplicationRecord
  include AASM

  belongs_to :user
  has_many :attachments

  aasm column: :status do
    state :draft, initial: true
    state :pending
    state :approved
    state :rejected

    event :submit_for_review do
      transitions from: :draft, to: :pending
    end

    event :approve do
      transitions from: :pending, to: :approved
    end

    event :reject do
      transitions from: :pending, to: :rejected
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: { user: "user", admin: "admin" }
  has_many :posts

  validates :name, presence: true
  validates :region, presence: true, if: -> { user? }
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def new; end

  def assign_admin_role
    @user = User.find(params[:user_id])
    @user.update(role: 'admin')
    redirect_to root_path, notice: 'User role updated to admin.'
  end

  private

  def user_params
    params.require(:user).permit(:user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protected

  def authenticate_admin!
    unless current_user&.admin?
      flash[:alert] = "You are not authorized to access this page."
      redirect_to root_path
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy, :submit_for_review, :approve, :reject]
  before_action :authorize_user, except: [:index, :new, :create, :generate_report]

  def index
    @user_posts = current_user.posts
    if current_user.admin?
      @posts = Post.where(status: :pending) # Администраторы видят только посты на проверке
    else
      @posts = Post.where(status: :approved)
    end
    filter_posts
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if current_user.admin?
      @post.status = :approved # Изменение состояния на :approved
    end

    if @post.save
      params[:post][:attachments]&.each do |a|
        @attachment = @post.attachments.create!(file: a)
      end

      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  def generate_report
    @posts = Post.all.where(status: 'approved')
    respond_to do |format|
      format.xlsx {
        render xlsx: 'generate_report'
      }
    end
  end

  def submit_for_review
    if @post.draft?
      PostStateChangeJob.perform_later(@post.id, 'submit_for_review')
      redirect_to @post, notice: 'Post has been sent for approval'
    end
  end

  def approve
    if @post.pending?
      PostStateChangeJob.perform_later(@post.id, 'approve')
      redirect_to @post, notice: 'Post has been approved'
    end
  end

  def reject
    if @post.pending?
      PostStateChangeJob.perform_later(@post.id, 'reject')
      redirect_to @post, notice: 'Post has been rejected'
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :status, :region)
  end

  def authorize_user
    unless current_user.admin? || @post.user == current_user
      redirect_to posts_path, alert: "You are not authorized to perform this action."
    end
  end

  def filter_posts
    @posts = @posts.where(region: params[:region]) if params[:region].present?
  end
end

app/controllers/user_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: 'User was successfully created.'
    else
      render :assign_admin_role
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :region, :role)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :name, :region])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :password_confirmation, :name, :region])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/new.html.erb
<h1>Assign Admin Role</h1>

<%= form_with(model: @user, url: assign_admin_role_admin_users_path, method: :patch) do |form| %>
  <div class="field">
    <%= form.label :user_id, "Select User" %>
    <%= form.collection_select :user_id, User.all, :id, :email, prompt: "Select User" %>
  </div>

  <div class="actions">
    <%= form.submit "Assign Admin Role" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestPosts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% flash.each do |key, message| %>
    <div class="flash <%= key %>">
      <%= message %>
    </div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_with(model: @post, url: post_path(@post), method: :patch) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region %>
  </div>

  <% if current_user.admin? || @post.draft? %>
    <div class="actions">
      <%= form.submit "Update Post" %>
    </div>
  <% end %>
<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if current_user %>
  <li><%= button_to "Sign out", destroy_user_session_path, method: :delete  %></li>
<% else %>
  <li><%= link_to "Sign up", new_user_registration_path %></li>
<% end %>
<%= link_to 'Download Report', generate_report_posts_path(format: :xlsx) %>

<h1>Posts</h1>

<%= form_tag(posts_path, method: :get) do %>
  <div class="field">
    <%= label_tag :region, "Region:" %>
    <%= select_tag :region, options_for_select(Post.distinct.pluck(:region)), include_blank: true %>
  </div>

  <%= submit_tag "Filter" %>
<% end %>

<% if current_user.admin? %>
  <p>Welcome, <%= current_user.name %> (Admin)</p>
  <p><%= link_to 'Assign Admin Role', new_admin_user_path %></p>
<% else %>
  <p>Welcome, <%= current_user.name %> (User)</p>
<% end %>

<% if current_user.admin? %>
  <%= link_to 'New Post', new_post_path %>
<% else %>
  <%= link_to 'New Draft', new_post_path %>
<% end %>

<% if current_user.admin? %>
  <% @posts.each do |post| %>
    <% if post.pending? %>
      <p><%= post.content %> - <strong>Pending</strong></p>
      <%= button_to 'Approve', approve_post_path(post), method: :put %>
      <%= button_to 'Reject', reject_post_path(post), method: :put %>
    <% end %>
  <% end %>
<% else %>
  <% @user_posts.each do |post| %>
    <% if post.draft? %>
      <p><%= post.content %> - <strong>Draft</strong></p>
      <%= button_to 'Edit', edit_post_path(post) %>
      <%= button_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= button_to 'Submit for Review', submit_for_review_post_path(post), method: :put %>
    <% end %>
  <% end %>

  <% @posts.each do |post| %>
    <p><%= post.content %> - <%= post.user.name %>, <strong><%= post.region %></strong></p>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<%= form_with(model: @post, url: posts_path, method: :post, multipart: true) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :content %>
  <%= form.text_area :content %>

  <% if current_user.user? %>
    <%= form.label :region, "Region (#{current_user.region})" %>
    <%= form.hidden_field :region, value: current_user.region %>
  <% else %>
    <%= form.label :region %>
    <%= form.text_field :region %>
  <% end %>

  <%= form.label :attachments %>
  <%= file_field_tag "post[attachments][]" %>

  <%= form.submit "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.content %></p>
<p>Region: <%= @post.region %></p>

<% if @post.attachments.present? %>
  <h3>Attachments:</h3>
  <ul>
    <% @post.attachments.each do |attachment| %>
      <%=  %>
      <li><%= link_to attachment.file.url, target: "_blank" do %>
          <%= attachment.file.identifier %>
        <% end %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>